{"id": "121687", "title": "Bug 121687: Exception throws when exporting data in a table inside a grid cell", "description": "", "OB": "", "EB": "When exporting data in two tables, the expected result is that the data is exported successfully. However, the actual result is that an exception occurs during the execution of ReportEngineService.getMetaData().", "SR": ""}