{"id": "5340", "title": "Bug 5340: Cancelling add exception breakpoint has no effect", "description": "", "OB": "When attempting to cancel the process of adding an exception breakpoint, the progress dialog immediately closes. However, the exception is still added to the list despite the cancellation request. Additionally, the cancel button should either disable or effectively cancel the operation. Currently, the operation continues despite the cancellation.", "EB": "The progress dialog should honor the cancellation request and abort the process of adding the exception breakpoint. Alternatively, the cancel button should be disabled when calling ProgressMonitorDialog.run and passing 'false' for the 'cancellable' parameter.", "SR": "To reproduce the issue: \n1) Navigate to the breakpoints pane in the debug perspective.\n2) Click the 'Add Exception' button.\n3) In the progress dialog, click the 'Cancel' button."}