{"id": "5340", "title": "Bug 5340 - Cancelling add exception breakpoint has no effect", "description": "When attempting to add an exception breakpoint and then cancelling the process, the breakpoint is still added and has functionality, despite the user's intention to cancel. This behavior is unexpected and should be resolved.", "OB": "When following the steps to add an exception breakpoint and then cancelling the process, the breakpoint is still added and functions as if it had been successfully added.", "EB": "When cancelling the process of adding an exception breakpoint, the breakpoint should not be added and should have no functionality. It should be as if the user had never attempted to add the breakpoint in the first place.", "SR": "1) Open the debug perspective and go to the breakpoints pane\n2) Click the J! button to add an exception breakpoint\n3) In the progress dialog, click cancel"}