{"bug_id": "51929", "title": "Bug 51929Advice calling protected super method causing java.lang.VerifyError 'Bad access to protected data'", "description": "A java.lang.VerifyError is thrown at runtime complaining about 'Bad access toprotected data' when advice, on a subaspect, that calls a protected method, onthe superaspect, is woven into a class.However another call to the same method woven into the same class but due toadvice declared in the superaspect works fine.The aspects were woven into precompiled (by sun's 1.4 javac) classes.The verify error occurs under both sun's 1.4 and blackdowns 1.3 VMs, and presumablyall VMs.Workaround:Making the protected method public fixes the verify error.A test case is available in CVS:tests/bugs/protectedvf/...tests/ajcTestFailing.xml"}