{"id": "5340", "title": "Bug 5340 - Cancelling add exception breakpoint has no effect", "description": "", "OB": "When adding an exception breakpoint and cancelling the process, the progress dialog closes immediately. However, despite the cancellation request, the exception list still comes up. This behavior contradicts the expectation that cancelling the process would either honor the cancellation request or disable the cancel button. To resolve this, when calling ProgressMonitorDialog.run, the 'cancellable' parameter should be set to 'false' to either honor the cancellation request or disable the cancel button.", "EB": "", "SR": ""}