{"id": "5340", "title": "Bug 5340 - Cancelling add exception breakpoint has no effect", "description": "", "OB": "When adding an exception breakpoint, if the user cancels the operation, the progress dialog closes immediately. However, after the operation is cancelled, the exception list still appears. The cancellation request should be honored and either the exception list should not appear at all, or the cancel button should be disabled. To fix this, when calling ProgressMonitorDialog.run, pass false for the 'cancellable' parameter. ", "EB": "", "SR": ""}