{"id": "5340", "title": "Bug 5340 - Cancelling add exception breakpoint has no effect", "description": "", "OB": "", "EB": "The progress dialog closes immediately. Eventually, the exception list comes up, ignoring the cancellation request. It should either honor the cancellation request or disable the cancel button (when calling ProgressMonitorDialog.run, pass false for the cancellable parameter).", "SR": "1) Go to the breakpoints pane in the debug perspective. 2) Click the J! button to add an exception. 3) In the progress dialog, click cancel."}