{"id": "121687", "title": "Bug 121687: Exception thrown when exporting data in table inside a grid cell", "description": "", "OB": "When exporting data in a table that is inside a grid cell, an exception is thrown. Specifically, the exception occurs in the 'ReportEngineService.getMetaData()' function.", "EB": "When exporting data in two tables, the expected result is that the data is successfully exported without any exceptions.", "SR": "To reproduce the issue:\n1. Insert a grid.\n2. Export data in two tables."}