{"id": "5340", "title": "Bug 5340: Cancelling add exception breakpoint has no effect", "description": "", "OB": "When adding an exception breakpoint, if the cancellation request is made, the progress dialog closes immediately. After that, the exception list comes up and it ignores the cancellation request. It should either honor the cancellation request or disable the cancel button. When calling ProgressMonitorDialog.run, make sure to pass false for the cancelable parameter.", "EB": "", "SR": ""}