{"id": "5340", "title": "Bug 5340: Cancelling add exception breakpoint has no effect", "description": "", "OB": "When adding an exception breakpoint, if the cancellation request is made by the user, the progress dialog should either honor the cancellation request or disable the cancel button. Currently, the progress dialog closes immediately but the exception list comes up, ignoring the cancellation request. To fix this, when calling 'ProgressMonitorDialog.run', 'false' should be passed for the 'cancellable' parameter.", "EB": "", "SR": "To reproduce the issue: \n1) Go to the breakpoints pane in the debug perspective. \n2) Click the J! button to add an exception. \n3) In the progress dialog, click cancel."}