{"id": "5340", "title": "Bug 5340 - Cancelling add exception breakpoint has no effect", "description": "", "OB": "When attempting to cancel the process of adding an exception breakpoint, the progress dialog closes immediately. Eventually, the exception list comes up despite the cancellation request, indicating that the cancellation request is being ignored. The expected behavior is that the cancellation request should be honored, and either the exception list should not come up or the cancel button should be disabled. To achieve this, when calling ProgressMonitorDialog.run, pass 'false' for the 'cancellable' parameter.", "EB": "", "SR": ""}